### PR TITLE
[WIP] Attempt windows

### PR DESCRIPTION
**Pull request by jaimergp**
(Sorry, previous one was a dirty branch from previous attempts)

Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@jaimergp, is this a project you hope to keep working on or should it be closed?

**Comment by jaimergp** [comment]
Sorry @xylar, I was on vacation last week. I think we are waiting for a new netcdf release. See #3 for more details!

**Comment by xylar** [comment]
Closed in favor of #78, which I believe incorporated a lot of this work. Thank you @jaimergp!

**Pull request closed without merging**
