### PR TITLE
Add Windows build

### LINKED ISSUE #3: Build on Windows
See https://github.com/Unidata/netcdf-fortran/issues/48#issuecomment-208321745

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #3 

This adds a `nompi` build for Windows using MinGW and follows the effort of @jaimergp in #52.

It suffers from the same problem that @jaimergp identified in https://github.com/conda-forge/netcdf-fortran-feedstock/issues/3#issuecomment-629788428, but this issue only appears in the Netcdf V2 compatibility layer, so I deactivated that. I think the issue stems from the different handling of `__declspec(dllexport)` and `__declspec(dllimport)` between the compiler that built `netcdf.{dll,lib}` and MinGW, but did not manage to make them work together. Looking at the relevant bits of `netcdf.{lib,h}`, I have the suspicion that it is actually a problem in the build of `libnetcdf`. Anyways, my suggestion is to take this on board as is and consider amending when and if we need V2 compact.

Actually, I think I figured out the problem now, and it is indeed in `libnetcdf`. Basically, in addition to the `extern` declarations in `netcdf.h`, also the definitions in https://github.com/Unidata/netcdf-c/blob/e4e29629dcac761c58b884bbe3088b444deecf0d/libdispatch/dv2i.c#L35-L37 need `__declspec(dll{export,import})`.

I'll upstream that with the other patches in this PR soon, but I think we can move forward here as is.

(For future reference: https://gcc.gnu.org/wiki/Visibility#How_to_use_the_new_C.2B-.2B-_visibility_support)

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
MinGW uses slightly different import libraries on Windows than MSVC, the most visible difference being the extension `.dll.a` instead of `.lib`. We could change that by using the Cmake facility of [`CMAKE_GNUtoMS`](https://cmake.org/cmake/help/latest/prop_tgt/GNUtoMS.html#prop_tgt:GNUtoMS), but since this library specifically offers Netcdf for Fortran, and Fortran users of this library will need a Fortran compiler as well, it seems reasonable to keep the MinGW version and assume the same compiler in downstream projects.

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@zklaus, I know next to nothing about windows so I'm unqualified to review. Thanks for this hard work! If you're happy, I'm happy and you can merge.

**Comment by xylar** [comment]
Ah, you can't merge yet!

**Comment by zklaus** [comment]
Thanks @xylar. On to esmf on Windows...

**Pull request merged**
