### PR TITLE
Merge build and host envs

### LINKED ISSUE #48: Wrong gfortran path from nc-config
Issue: `nc-config` reports the following gfortran compiler
```bash
$ nc-config --fc
/home/conda/feedstock_root/build_artifacts/netcdf-fortran_1585602845013/_build_env/bin/x86_64-conda_cos6-linux-gnu-gfortran
```
which breaks Makefile which relies on `nc-config --fc` to give the actual Fortran compiler that should be used.
I would expect it to return a bare `x86_64-conda_cos6-linux-gnu-gfortran`, or the path to the actual compiler in the active environment, e.g. in my case, `/home/jsalort/anaconda3/envs/py38/bin/x86_64-conda_cos6-linux-gnu-gfortran`.

But maybe I am wrong, and `nc-config` just always return the absolute path in the system in which it was built. But then, it hardly seems useful.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/jsalort/anaconda3/envs/py38:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
aiohttp                   3.6.2            py38h516909a_0    conda-forge
aiohttp-jinja2            1.2.0                    pypi_0    pypi
alabaster                 0.7.12                     py_0  
appdirs                   1.4.3              pyh91ea838_0  
argh                      0.26.2                   py38_0  
astroid                   2.4.0                    py38_0  
async-timeout             3.0.1                    py38_0  
atomicwrites              1.4.0                      py_0  
attrs                     19.3.0                     py_0  
autoconf                  2.69            pl526h14c3975_9    conda-forge
automake                  1.16.2                  pl526_0    conda-forge
autopep8                  1.4.4                      py_0  
babel                     2.8.0                      py_0  
backcall                  0.1.0                    py38_0  
bibtexparser              1.1.0                    pypi_0    pypi
binutils-meta             1.0.4                         0    conda-forge
binutils_impl_linux-64    2.33.1               he6710b0_7  
binutils_linux-64         2.33.1              h9595d00_17    conda-forge
black                     19.10b0                    py_0  
blas                      1.0                    openblas  
bleach                    3.1.4                      py_0  
bzip2                     1.0.8                h7b6447c_0  
c-compiler                1.0.4                h516909a_0    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cairo                     1.16.0            hcf35c78_1003    conda-forge
certifi                   2020.4.5.1       py38h32f6830_0    conda-forge
cffi                      1.14.0           py38h2e261b9_0  
cfgv                      3.1.0                      py_0    conda-forge
chardet                   3.0.4                 py38_1003  
click                     7.1.2                      py_0  
cloudpickle               1.4.1                      py_0  
commonmark                0.7.5                      py_0    conda-forge
compilers                 1.0.4                         0    conda-forge
conda                     4.8.3                    py38_0  
conda-package-handling    1.6.1            py38h7b6447c_0  
convbox                   0.2                       dev_0    <develop>
cryptography              2.9.2            py38h1ba5d50_0  
curl                      7.69.1               hbc83047_0  
cxx-compiler              1.0.4                hc9558a2_0    conda-forge
cycler                    0.10.0                   py38_0  
cython                    0.29.17          py38he6710b0_0  
cytoolz                   0.10.1           py38h7b6447c_0  
dask-core                 2.16.0                     py_0  
dbus                      1.13.14              hb2f20db_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
diff-match-patch          20181111                   py_0  
distro                    1.5.0                    pypi_0    pypi
docutils                  0.16                     py38_0  
editdistance              0.5.3            py38h950e882_0    conda-forge
entrypoints               0.3                      py38_0  
et_xmlfile                1.0.1                    py38_0  
expat                     2.2.6                he6710b0_0  
ffmpeg                    4.2.2                h20bf706_0  
fftw                      3.3.8           nompi_h7f3a6c3_1110    conda-forge
filelock                  3.0.12                     py_0  
flake8                    3.7.9                    py38_0  
flask                     1.1.2                      py_0  
fluiddyn                  0.3.2                     dev_0    <develop>
fluidlab                  0.1.0                     dev_0    <develop>
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
fortran-compiler          1.0.4                he991be0_0    conda-forge
freetype                  2.9.1                h8a8886c_1  
future                    0.18.2                   py38_0  
gcc_impl_linux-64         7.3.0                hd420e75_5    conda-forge
gcc_linux-64              7.3.0               h553295d_17    conda-forge
gfortran_impl_linux-64    7.3.0                hdf63c60_5    conda-forge
gfortran_linux-64         7.3.0               h553295d_17    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
git                       2.23.0          pl526hacde149_0  
glib                      2.63.1               h5a9c865_0  
gmp                       6.1.2                h6c8ec71_1  
gnutls                    3.6.5             h71b1129_1002  
graphite2                 1.3.13               h23475e2_0  
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_5    conda-forge
gxx_linux-64              7.3.0               h553295d_17    conda-forge
h5netcdf                  0.8.0                    pypi_0    pypi
h5py                      2.10.0          nompi_py38h513d04c_102    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
identify                  1.4.15             pyh9f0ad1d_0    conda-forge
idna                      2.9                        py_1  
imageio                   2.8.0                      py_0  
imagesize                 1.2.0                      py_0  
importlib_metadata        1.5.0                    py38_0  
intervaltree              3.0.2                      py_0  
ipykernel                 5.1.4            py38h39e3cac_0  
ipympl                    0.3.3                      py_0  
ipython                   7.13.0           py38h5ca1d4c_0  
ipython_genutils          0.2.0                    py38_0  
ipywidgets                7.5.1                      py_0  
isort                     4.3.21                   py38_0  
itsdangerous              1.1.0                      py_0  
jasper                    1.900.1              hd497a04_4  
jdcal                     1.4.1                      py_0  
jedi                      0.15.2                   py38_0  
jeepney                   0.4.3                      py_0  
jinja2                    2.11.2                     py_0  
jpeg                      9c                h14c3975_1001    conda-forge
json5                     0.9.4                      py_0  
jsonschema                3.2.0                    py38_0  
jupyter_client            6.1.3                      py_0  
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.3                    py38_0  
jupyterlab                1.2.6              pyhf63ae98_0  
jupyterlab_server         1.1.1                      py_0  
keyring                   21.1.1                   py38_2  
kiwisolver                1.2.0            py38hfd86e86_0  
krb5                      1.17.1               h173b8e3_0  
lame                      3.100                h7b6447c_0  
latexcodec                2.0.0                      py_0    conda-forge
lazy-object-proxy         1.4.3            py38h7b6447c_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.69.1               h20c2e04_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0  
libgomp                   9.2.0                h24d8f2e_2    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
liblapacke                3.8.0               16_openblas    conda-forge
libllvm9                  9.0.1                he513fc3_1    conda-forge
libnetcdf                 4.7.4           nompi_h9f9fd6a_101    conda-forge
libopenblas               0.3.9                h5ec1e0e_0    conda-forge
libopencv                 4.2.0                    py38_5    conda-forge
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.16               h1bed415_0  
libspatialindex           1.9.3                he6710b0_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libvpx                    1.7.0                h439df22_0  
libwebp                   1.0.2                h56121f0_5    conda-forge
libxcb                    1.13                 h1bed415_1  
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.9                hea5a465_1  
llc                       0.2.0                    pypi_0    pypi
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
llvmlite                  0.32.1           py38hd408876_0  
m4                        1.4.18            h14c3975_1001    conda-forge
make                      4.3                  h516909a_0    conda-forge
markdown                  3.1.1                    py38_0  
markupsafe                1.1.1            py38h7b6447c_0  
matplotlib                3.2.1                         0    conda-forge
matplotlib-base           3.2.1            py38h2af1d28_0    conda-forge
mccabe                    0.6.1                    py38_1  
mercurial                 5.4              py38h1e0a361_0    conda-forge
minimalmodbus             1.0.2                    pypi_0    pypi
mistune                   0.8.4           py38h7b6447c_1000  
more-itertools            8.2.0                      py_0  
multidict                 4.7.3            py38h7b6447c_0  
mypy_extensions           0.4.3                    py38_0  
nbconvert                 5.6.1                    py38_0  
nbformat                  5.0.6                      py_0  
nbsphinx                  0.7.0              pyh9f0ad1d_0    conda-forge
ncurses                   6.2                  he6710b0_1  
netcdf-fortran            4.5.2           nompi_h45d7149_104    conda-forge
nettle                    3.4.1                hbb512f6_0  
networkx                  2.4                        py_0  
nidaqmx                   0.5.7                    pypi_0    pypi
nodeenv                   1.3.5                      py_0    conda-forge
nodejs                    10.13.0              he6710b0_0  
notebook                  6.0.3                    py38_0  
nptdms                    0.26.0             pyh9f0ad1d_0    conda-forge
nspr                      4.22                 he6710b0_0  
nss                       3.46.1               hab99668_0  
numba                     0.49.1           py38h0573a6f_0  
numpy                     1.18.1           py38h94c655d_0  
numpy-base                1.18.1           py38h2f8d375_1  
numpy_groupies            0.9.10                     py_0    conda-forge
numpydoc                  0.9.2                      py_0  
olefile                   0.46                       py_0  
opencv                    4.2.0                    py38_5    conda-forge
opencv-contrib-python     4.2.0.34                 pypi_0    pypi
openh264                  2.1.0                hd408876_0  
openpyxl                  3.0.3                      py_0  
openssl                   1.1.1g               h516909a_0    conda-forge
oset                      0.1.3                      py_1    conda-forge
packaging                 20.3                       py_0  
pandas                    1.0.3            py38h0573a6f_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py38_1  
parso                     0.5.2                      py_0  
pathspec                  0.7.0                      py_0  
pathtools                 0.1.2                      py_1  
pcre                      8.43                 he6710b0_0  
perl                      5.26.2               h14c3975_0  
pexpect                   4.8.0                    py38_0  
pickleshare               0.7.5                 py38_1000  
pillow                    7.1.2            py38hb39fc2d_0  
pint                      0.11                       py_1    conda-forge
pip                       20.0.2                   py38_3  
pixman                    0.38.0               h7b6447c_0  
pluggy                    0.13.1                   py38_0  
pre-commit                2.4.0            py38h32f6830_0    conda-forge
progressbar2              3.37.1                   py38_0  
prometheus_client         0.7.1                      py_0  
prompt-toolkit            3.0.4                      py_0  
prompt_toolkit            3.0.4                         0  
psutil                    5.7.0            py38h7b6447c_0  
ptyprocess                0.6.0                    py38_0  
py                        1.8.1                      py_0  
py-opencv                 4.2.0            py38h23f93f0_5    conda-forge
pybtex                    0.22.2           py38h32f6830_1    conda-forge
pybtex-docutils           0.2.2            py38h32f6830_1    conda-forge
pycodestyle               2.5.0                    py38_0  
pycosat                   0.6.3            py38h7b6447c_1  
pycparser                 2.20                       py_0  
pydaqmx                   1.4.3                    pypi_0    pypi
pydocstyle                4.0.1                      py_0  
pyflakes                  2.1.1                    py38_0  
pygments                  2.6.1                      py_0  
pyheliumhp                0.1                      pypi_0    pypi
pyheliumper               0.1                       dev_0    <develop>
pyheliumxa                0.1                      pypi_0    pypi
pylint                    2.5.0                    py38_1  
pymanip                   0.3.2                     dev_0    <develop>
pyopenssl                 19.1.0                   py38_0  
pyparsing                 2.4.7                      py_0  
pyqt                      5.12.3           py38ha8c2ead_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtgraph                 0.10.0             pyh91ea838_3  
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.16.0           py38h7b6447c_0  
pyserial                  3.4                      py38_0  
pysocks                   1.7.1                    py38_0  
pytest                    5.4.1                    py38_0  
pytest-runner             5.2                        py_0  
python                    3.8.2                hcf32534_0  
python-dateutil           2.8.1                      py_0  
python-jsonrpc-server     0.3.4                      py_0  
python-language-server    0.31.10                  py38_0  
python-utils              2.3.0                    py38_0  
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1                     py_0  
pyvisa                    1.10.1           py38h32f6830_3    conda-forge
pyvisa-py                 0.3.1                      py_2    conda-forge
pywavelets                1.1.1            py38h7b6447c_0  
pyxdg                     0.26                       py_0  
pyyaml                    5.3.1            py38h7b6447c_0  
pyzmq                     18.1.1           py38he6710b0_0  
qdarkstyle                2.8.1                      py_0  
qt                        5.12.5               hd8c4c69_1    conda-forge
qtawesome                 0.7.0                      py_0  
qtconsole                 4.7.3                      py_0  
qtpy                      1.9.0                      py_0  
readline                  8.0                  h7b6447c_0  
regex                     2020.4.4         py38h7b6447c_0  
requests                  2.23.0                   py38_0  
rope                      0.17.0                     py_0  
rtree                     0.9.4                    py38_1  
ruamel_yaml               0.15.87          py38h7b6447c_0  
scikit-image              0.16.2           py38h0573a6f_0  
scipy                     1.4.1            py38habc2bb6_0  
secretstorage             3.1.2                    py38_0  
send2trash                1.5.0                    py38_0  
setuptools                46.2.0                   py38_0  
six                       1.14.0                   py38_0  
snowballstemmer           2.0.0                      py_0  
sortedcontainers          2.1.0                    py38_0  
sphinx                    3.0.3                      py_0  
sphinx-argparse           0.2.5                      py_0    conda-forge
sphinx_rtd_theme          0.4.3                      py_0  
sphinxcontrib-applehelp   1.0.2                      py_0  
sphinxcontrib-bibtex      1.0.0                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0  
sphinxcontrib-htmlhelp    1.0.3                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.3                      py_0  
sphinxcontrib-serializinghtml 1.1.4                      py_0  
spyder                    4.1.3                    py38_0  
spyder-kernels            1.9.1                    py38_0  
sqlite                    3.31.1               h62c20be_1  
tbb                       2020.0               hfd86e86_0  
terminado                 0.8.3                    py38_0  
testpath                  0.4.4                      py_0  
tk                        8.6.10               hed695b0_0    conda-forge
toml                      0.10.0             pyh91ea838_0  
toolz                     0.10.0                     py_0  
tornado                   6.0.4            py38h7b6447c_1  
tqdm                      4.46.0                     py_0  
traitlets                 4.3.3                    py38_0  
typed-ast                 1.4.1            py38h7b6447c_0  
typing_extensions         3.7.4.1                  py38_0  
ujson                     1.35             py38h7b6447c_0  
urllib3                   1.25.8                   py38_0  
virtualenv                16.7.5                     py_0  
watchdog                  0.10.2                   py38_0  
wcwidth                   0.1.9                      py_0  
webencodings              0.5.1                    py38_1  
werkzeug                  1.0.1                      py_0  
wheel                     0.34.2                   py38_0  
widgetsnbextension        3.5.1                    py38_0  
wrapt                     1.11.2           py38h7b6447c_0  
wurlitzer                 2.0.0                    py38_0  
x264                      1!157.20191217       h7b6447c_0  
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h7b6447c_0  
yaml                      0.1.7                had09818_2  
yapf                      0.28.0                     py_0  
yarl                      1.4.2            py38h7b6447c_0  
zeromq                    4.3.1                he6710b0_3  
zipp                      3.1.0                      py_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : py38
    active env location : /home/jsalort/anaconda3/envs/py38
            shell level : 2
       user config file : /home/jsalort/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.28
       base environment : /home/jsalort/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jsalort/anaconda3/pkgs
                          /home/jsalort/.conda/pkgs
       envs directories : /home/jsalort/anaconda3/envs
                          /home/jsalort/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Linux/4.19.0-8-amd64 debian/10 glibc/2.28
                UID:GID : 45177:100
             netrc file : None
           offline mode : False
```
</details>

### PR DESCRIPTION
**Pull request by xylar**
This should fix the issue with prefix replacement.

closes #48 

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I tested this locally on my laptop and was able to get the expected path from `nc-config --fc`:
```
$ conda build -m .ci_support/linux_mpinompi.yaml recipe
$ conda create -n test --use-local netcdf-fortran
$ conda activate test
$ nc-config --fc
/home/xylar/miniconda3/envs/test/bin/x86_64-conda_cos6-linux-gnu-gfortran
```

**Comment by xylar** [comment]
@beckermr, thanks for your suggestion on this!

**Comment by beckermr** [comment]
@xylar Can we add this as a test to the recipe?

**Comment by xylar** [comment]
Yep, I'm adding one in #50.

**Pull request merged**
