### PR TITLE
Add windows build

### LINKED ISSUE #3: Build on Windows
See https://github.com/Unidata/netcdf-fortran/issues/48#issuecomment-208321745

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #3, is subordinate to #52.

The purpose of this PR is to try to figure out a way to build this on windows with the regular toolchain. If and when #52 is ready, that one should take precedence.

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please restart ci

**Comment by xylar** [comment]
maybe rebase and take out the old rerender?  But maybe it doesn't really matter?

**Comment by zklaus** [comment]
I was surprised to find that it actually already sits on the latest main. I think we are ok. I just wanted a new build for debugging because the old logs are gone by now.

**Comment by xylar** [comment]
Yep, that's what I figured.

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
Seems like flang simply is not ready for prime-time use, so I am continuing in #78 with the work that @jaimergp started in #52, i.e. a MinGW based windows build.

**Pull request closed without merging**
