### PR TITLE
Remove manual pins for mingw

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
As discussed in #90, I'm not bumping the build number because I don't expect anything to change.  I just want to prevent trouble in future migrations.

**Comment by xylar** [comment]
Great, no need to bump the build number as I suspected.

**Comment by zklaus** [comment]
Thanks for taking care of this, @xylar!

**Pull request merged**
